### ISSUE TITLE
Jamf Device Migrator 

### ISSUE THREAD

**Issue by mani2care** [PezzaD84/Jamf-Device-Migrator#1]
Really great idea but instead of asking user to enroll the device can create the quickadd package and put in to the device and run it right ? So use no need to go and enroll the device manually it’s alternet option 
Or I think there was one script to call and install the mdm

**Comment by PezzaD84** [comment]
Hi,

Thanks for your feedback it's always appreciated to hear other people's ideas.
Since Big Sur the quick add package no longer works due to apple changing how MDM profiles are installed. This now has to be done by the user or local admin unless the device is DEP enrolled.
